name: release
on: release

jobs:
  publish:
    strategy:
      matrix:
        java: [ 16 ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Artifacts
      - name: publish
        uses: Kir-Antipov/mc-publish@v1.1
        with:
          modrinth-id: 2VlI1Toh
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 532078
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          files-primary: "!(*-@(dev|sources)).jar"
          files-secondary: "*-@(dev|sources).jar"

          loaders: fabric
          java: 16